import React from 'react'

const Blog = () => {
  return (
    <div>
       coming soon ...

       <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem omnis error libero minus, accusantium dolores, mollitia asperiores excepturi sapiente est quidem perferendis adipisci consequatur eligendi ut id illum nostrum laborum nulla tempora nam voluptates cupiditate reiciendis a. Magnam fugit reprehenderit, ea explicabo iste officiis vitae ipsum rem tenetur, dicta perferendis praesentium sint culpa! Maxime ad eveniet, facere ullam deleniti dolores iusto nostrum pariatur cumque ducimus asperiores similique expedita. Ex obcaecati a saepe perferendis deserunt, blanditiis ratione animi, vero aliquid sunt voluptatibus? Necessitatibus, odit modi, possimus amet a voluptate ipsam quasi animi sapiente neque facere voluptatibus quidem! Doloremque, laborum assumenda? Tempora.</p>
       
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et accusantium modi blanditiis deleniti optio delectus eaque quisquam? Tempora rem repellendus debitis odit molestias voluptates, mollitia necessitatibus consequatur inventore, doloribus quos facilis ab quo veniam recusandae? Excepturi commodi ipsam voluptate molestias hic? Asperiores libero, tempore voluptates autem non rerum voluptas necessitatibus voluptatibus facilis minus expedita molestiae repudiandae reiciendis iste optio velit unde! Omnis sed fuga commodi accusamus quos dolor illo odit tempora eius nemo laborum aspernatur necessitatibus molestiae doloribus magni ullam, debitis atque quas. Vero, ab. Praesentium architecto minus at reiciendis inventore. Sed maiores quia suscipit ab cupiditate porro dicta, quam voluptas veniam cum fugiat reprehenderit voluptatem consectetur eligendi dolorem laudantium nostrum atque quidem accusantium beatae? Culpa maiores quaerat fugiat fuga libero, molestias asperiores debitis aliquid nobis beatae dolores eligendi voluptates veritatis quasi quod error delectus, blanditiis ad esse perspiciatis minus sequi voluptatum iste? Harum perspiciatis in ipsam expedita quibusdam accusantium esse quas repellendus distinctio omnis. Maxime, possimus delectus placeat doloremque labore dolores tempore alias sed dolorem corrupti est! Voluptas, nesciunt veritatis sapiente facere velit quae blanditiis ipsa autem dolores ullam in qui officia deleniti minima unde dignissimos impedit nisi repudiandae! Iusto maxime cupiditate accusantium magnam possimus quam asperiores sit dolorem?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et accusantium modi blanditiis deleniti optio delectus eaque quisquam? Tempora rem repellendus debitis odit molestias voluptates, mollitia necessitatibus consequatur inventore, doloribus quos facilis ab quo veniam recusandae? Excepturi commodi ipsam voluptate molestias hic? Asperiores libero, tempore voluptates autem non rerum voluptas necessitatibus voluptatibus facilis minus expedita molestiae repudiandae reiciendis iste optio velit unde! Omnis sed fuga commodi accusamus quos dolor illo odit tempora eius nemo laborum aspernatur necessitatibus molestiae doloribus magni ullam, debitis atque quas. Vero, ab. Praesentium architecto minus at reiciendis inventore. Sed maiores quia suscipit ab cupiditate porro dicta, quam voluptas veniam cum fugiat reprehenderit voluptatem consectetur eligendi dolorem laudantium nostrum atque quidem accusantium beatae? Culpa maiores quaerat fugiat fuga libero, molestias asperiores debitis aliquid nobis beatae dolores eligendi voluptates veritatis quasi quod error delectus, blanditiis ad esse perspiciatis minus sequi voluptatum iste? Harum perspiciatis in ipsam expedita quibusdam accusantium esse quas repellendus distinctio omnis. Maxime, possimus delectus placeat doloremque labore dolores tempore alias sed dolorem corrupti est! Voluptas, nesciunt veritatis sapiente facere velit quae blanditiis ipsa autem dolores ullam in qui officia deleniti minima unde dignissimos impedit nisi repudiandae! Iusto maxime cupiditate accusantium magnam possimus quam asperiores sit dolorem?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et accusantium modi blanditiis deleniti optio delectus eaque quisquam? Tempora rem repellendus debitis odit molestias voluptates, mollitia necessitatibus consequatur inventore, doloribus quos facilis ab quo veniam recusandae? Excepturi commodi ipsam voluptate molestias hic? Asperiores libero, tempore voluptates autem non rerum voluptas necessitatibus voluptatibus facilis minus expedita molestiae repudiandae reiciendis iste optio velit unde! Omnis sed fuga commodi accusamus quos dolor illo odit tempora eius nemo laborum aspernatur necessitatibus molestiae doloribus magni ullam, debitis atque quas. Vero, ab. Praesentium architecto minus at reiciendis inventore. Sed maiores quia suscipit ab cupiditate porro dicta, quam voluptas veniam cum fugiat reprehenderit voluptatem consectetur eligendi dolorem laudantium nostrum atque quidem accusantium beatae? Culpa maiores quaerat fugiat fuga libero, molestias asperiores debitis aliquid nobis beatae dolores eligendi voluptates veritatis quasi quod error delectus, blanditiis ad esse perspiciatis minus sequi voluptatum iste? Harum perspiciatis in ipsam expedita quibusdam accusantium esse quas repellendus distinctio omnis. Maxime, possimus delectus placeat doloremque labore dolores tempore alias sed dolorem corrupti est! Voluptas, nesciunt veritatis sapiente facere velit quae blanditiis ipsa autem dolores ullam in qui officia deleniti minima unde dignissimos impedit nisi repudiandae! Iusto maxime cupiditate accusantium magnam possimus quam asperiores sit dolorem?</p>
    </div>
  )
}

export default Blog
